name: admin-client
on:
  push:
    branches:
      - master
    paths:
      - 'src/ParkSharing.Admin.Client/**'
      - 'src/ParkSharing.ServiceDefaults/**'
      - 'src/ParkSharing.Shared/**'

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
  docker:
    uses: ObseumEU/github-workflows/.github/workflows/build-and-push.yml@master
    with:
      context: src/ParkSharing.Admin.Client
      tests: false
      image: smixers/parksharing-admin-client
      dockerfile: src/ParkSharing.Admin.Client/Dockerfile
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      DOCKER_USER: ${{ secrets.DOCKER_SMIXERS_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_SMIXERS_SECRET }}